- name: install
  hosts: node3
  become: true

  tasks:
    - name: create_directory
      file:
        path: /home/vlad/node-exporter
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy_compose_to_server
      copy:
        dest: /home/vlad/node-exporter/docker-compose.yml
        content: |
          version: "3.9"
          services:
            node-exporter:
              image: prom/node-exporter:v1.3.1
              ports:
                - "9100:9100"
              volumes:
                - /proc:/host/proc:ro
                - /sys:/host/sys:ro
                - /:/rootfs:ro
              command:
                - '--path.procfs=/host/proc'
                - '--path.sysfs=/host/sys'
                - '--collector.filesystem.mount-points-exclude'
                - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

    - name: start_docker_compose
      command: docker-compose up -d
      args:
        chdir: /opt/node-exporter

    - name: check_container_status
      shell: "docker ps --format '{{.Names}}' | grep -w node-exporter"
      register: container_check
      failed_when: container_check.rc != 0
      changed_when: false
